theme: jekyll-theme-cayman
title: Welcome to Valentine Wu’s Homepage at GitHub!
description: Being a Full Stack Java 8 & JavaScript (ES6+) Developer. Feel free to contact me at valentine.sfu@gmail.com.
